#!/usr/bin/env bash
# script

get_subdomain_info() {
    domain=\$1
    subdomain=\$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        result=$(dig $sub.$domain | grep -A1 'ANSWER SECTION:')
        record_type=$(echo $result | awk '{print \$4}')
        destination=$(echo $result | awk '{print \$5}')
        echo "The subdomain $sub is a $record_type record and points to $destination"
    done
}

get_subdomain_info \$1 \$2
