#!/usr/bin/env bash

# Function to display usage
display_usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

if [ "$#" -ne 4 ]; then
    display_usage
    exit 1
fi

# Assign the arguments to variables
path_to_file="$1"
ip="$2"
username="$3"
path_to_ssh_key="$4"

# Perform  transfer
scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
