#!/usr/bin/env bash
# install nginx
sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"
echo "Holberton School" | tee -a /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
service nginx start
