#!/usr/bin/env bash
# Script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers using roundrobin algorithm
# Ensure HAProxy can be managed via an init script

# Update system packages and install HAProxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure HAProxy
haproxy_config="\
frontend  yonas-frontend
        bind *:80
        mode http
        default_backend yonas-backend
backend yonas-backend
        balance roundrobin
        server 63210-web-01 54.196.201.51:80 check
        server 63210-web-02 54.237.73.120:80 check
"
echo "$haproxy_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable HAProxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart HAProxy service
sudo service haproxy restart

