#!/usr/bin/env bash
# Load balancer setup

# Install necessary software
sudo apt-get -y install software-properties-common

# Add HAProxy repository
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8

# Update system packages
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# Enable HAProxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 

# Configure HAProxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver web-server-1 54.196.201.51:80 check\n\tserver web-server-2 54.237.73.120:80 check\n' /etc/haproxy/haproxy.cfg

# Restart HAProxy service
sudo service haproxy restart

