#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100

for (( x=1; x < 101; x++ ))
do
    if (( x % 15 == 0 )); then
	echo "FizzBuzz"
    elif (( x % 3 == 0 )); then
	echo "Fizz"
    elif (( x % 5 == 0 )); then
	echo "Buzz"
    else
	echo "$x"
    fi
done
